//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string ADDDRESSS { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public byte[] PICTURE { get; set; }
        public string IDCARD { get; set; }
        public Nullable<int> DEGREEID { get; set; }
        public Nullable<int> POSITIONID { get; set; }
        public Nullable<int> DEPARTMENTID { get; set; }
        public Nullable<int> INSURANCEID { get; set; }
    
        public virtual DEGREE DEGREE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual INSURANCE INSURANCE { get; set; }
        public virtual POSITION POSITION { get; set; }
    }
}
