//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSURANCE()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public int INSURANCEID { get; set; }
        public Nullable<int> EID { get; set; }
        public string ISSUEDBY { get; set; }
        public string HOSPITAL { get; set; }
        public Nullable<System.DateTime> DATEBUY { get; set; }
        public Nullable<System.DateTime> EXPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
